// This file was generated by Gemini as a test to see how it compares 
// to Grok and ChatGPT, which have been my primary AI tools at work.

// This file was generated by Gemini as a test to see how it compares 
// to Grok and ChatGPT, which have been my primary AI tools at work.
//
// It's really bad tho... stuttery, uses 90% CPU, poor animation, needs requestAnimationFrame
// Also, it ignored my instructions, and didnt use GSAP hooks... And canvas is not completely necessary, though faster (when done right).

import { useEffect, useRef } from 'react';
import gsap from 'gsap';

export default function MatrixRain() {
    const canvasRef = useRef<HTMLCanvasElement>(null);

    useEffect(() => {
        const canvas = canvasRef.current;
        if (!canvas) return;

        const ctx = canvas.getContext('2d');
        if (!ctx) return;

        const fontSize = 16;
        const chars = '01ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789$+-*/=%<>#!&'.split('');
        let columns = 0;
        let drops: number[] = [];

        const resize = () => {
            canvas.height = 200;

            columns = Math.floor(canvas.width / fontSize);

            drops = Array(columns).fill(1).map(() => Math.random() * -100);
        };

        window.addEventListener('resize', resize);
        resize();

        const update = () => {
            ctx.fillStyle = 'rgba(0, 0, 0, 0.05)';
            ctx.fillRect(0, 0, canvas.width, canvas.height);

            ctx.fillStyle = '#0F0'; // Matrix Green
            ctx.font = `${fontSize}px monospace`;
            ctx.shadowBlur = 8; // The "shimmer/glow" effect
            ctx.shadowColor = '#0F0';

            for (let i = 0; i < drops.length; i++) {
                const text = chars[Math.floor(Math.random() * chars.length)];

                ctx.fillStyle = Math.random() > 0.95 ? '#FFF' : '#0F0';

                const x = i * fontSize;
                const y = drops[i] * fontSize;

                ctx.fillText(text, x, y);

                if (y > canvas.height && Math.random() > 0.99) {
                    drops[i] = 0;
                }

                drops[i]++;
            }
        };

        gsap.ticker.add(update);

        return () => {
            window.removeEventListener('resize', resize);
            gsap.ticker.remove(update);
        };
    }, []);

    return (
        <canvas
            ref={canvasRef}
            style={{
                display: 'block',
                position: 'absolute',

                top: 0,
                left: 0,
                right: 0,
                bottom: 0,
                zIndex: 0,

                width: '100%',
                height: '100%',
            }}
        />
    );
};
